name: 'Go Beautiful HTML Coverage'
description: 'A GitHub Action to track code coverage in your pull requests, with a beautiful HTML preview, for free.'
author: 'Kilian Ciuffolo'
branding:
  icon: 'bar-chart'
  color: 'green'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  branch:
    default: cover
    description: The branch to checkout or create and push coverage to.
  token:
    description: The token to use for pushing to the repository.
    default: ${{ github.token }}
  path:
    description: The relative path of your go project. Useful for monorepos and custom folder structures.
    default: './'
  threshold:
    description: The minimum % of coverage required.
    default: '0'
runs:
  using: composite
  steps:
    - name: Checkout Coverage Branch
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: go-cover
        token: ${{ inputs.token }}

    - name: Checkout Coverage Branch
      shell: bash
      run: |
        cd go-cover
        git fetch origin
        if git rev-parse --verify origin/${{ inputs.branch }}; then
          git checkout ${{ inputs.branch }}
          git pull origin ${{ inputs.branch }}
        else
          git checkout --orphan ${{ inputs.branch }}
          rm .git/index
          git clean -fdx
        fi

    - name: Push Coverage
      shell: bash
      run: |
        export REVISION="${{ github.event.pull_request.head.sha || github.sha }}"
        cd ${{ inputs.path }}
        go tool cover -func=cover.out -o cover.txt
        go tool cover -html=cover.out -o cover.html
        mv cover.html ${GITHUB_WORKSPACE}/go-cover/${REVISION}.html
        mv cover.txt ${GITHUB_WORKSPACE}/go-cover/${REVISION}.txt
        cd ${GITHUB_WORKSPACE}/go-cover
        ex -sc '%s/<style>/<style>@import url("nord.css");/' -c 'x' ${REVISION}.html
        ex -sc '%s/<\/script>/<\/script><script src="ln.js"><\/script>/' -c 'x' ${REVISION}.html
        cp ${GITHUB_ACTION_PATH}/assets/* .
        git add .
        git config user.email "go-coverage-action@github.com"
        git config user.name "go-coverage-action"
        git commit -m "chore: add cover for ${REVISION}" || true
        git push origin ${{ inputs.branch }}

    - name: Post Code Coverage Comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          const script = require(`${process.env.GITHUB_ACTION_PATH}/src/update-comment.js`)
          const revision = '${{ github.event.pull_request.head.sha || github.sha }}'
          const path = '${{ inputs.path }}'
          const threshold = parseFloat('${{ inputs.threshold }}', 10)
          await script({ context, github, path, revision, threshold })

    - name: Check Coverage Threshold
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          const script = require(`${process.env.GITHUB_ACTION_PATH}/src/check-threshold.js`)
          const revision = '${{ github.event.pull_request.head.sha || github.sha }}'
          const threshold = parseFloat('${{ inputs.threshold }}', 10)
          await script({ threshold, revision })
