name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Generate Coverage Files
        run: |
          cd go-test-app-01
          make test

      - name: Go Beautiful HTML Coverage
        if: always()
        uses: './'
        with:
          path: go-test-app-01/
          threshold: 66.7

      - name: Go Beautiful HTML Coverage
        uses: './'
        with:
          path: go-test-app-02/
