on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test
        run: make cover.html

      - uses: './'
        with:
          branch: 'cover'
